# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    app.cors_origin_autorisee: '%env(CORS_ORIGIN_AUTORISEE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\EventListener\CorsListener:
        arguments:
            $originAutorisee: '%app.cors_origin_autorisee%'
